#!/usr/bin/env python3
"""Run the authorization test matrix against the real api_sentinel and report.

    python3 tests/authz_matrix/run_matrix.py                    # run and print the summary
    python3 tests/authz_matrix/run_matrix.py --write            # also write results.csv and docs/TEST_MATRIX_RESULTS.md
    python3 tests/authz_matrix/run_matrix.py --update-baseline  # re-pin baseline.json

Counts are over a small, hand-built, adversarially chosen corpus. They are NOT detection rates.
Exit code 1 means the harness itself has a problem: an unlabeled finding, a fixture error, an oracle the independent
probe does not confirm, or a tool crash. Measured FP/FN are results, not runner failures.
"""
from __future__ import annotations

import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from authz_matrix import harness, scenarios  # noqa: E402
from authz_matrix.harness import DEVIATIONS, OUTCOME_ORDER  # noqa: E402

ROOT = HERE.parents[1]
BASELINE = HERE / "baseline.json"


def prediction_mismatches(results):
    """A gap annotation predicts a deviation. Report where the prediction was wrong, in either direction."""
    out = []
    for r in results:
        for t in r.rows:
            if t.label in (harness.POLICY, harness.INDET):
                continue
            predicted = bool(t.gap)
            observed = t.outcome in DEVIATIONS
            if predicted != observed:
                out.append((t, ("predicted a deviation, got " if predicted else "did not predict a deviation, got ")
                            + t.outcome))
    return out


def md_escape(x):
    return str(x).replace("|", "\\|")


def render_md(results):
    c = harness.counts(results)
    tot = harness.totals(results)
    L = ["# Authorization test matrix - generated results", "",
         "Generated by `python3 tests/authz_matrix/run_matrix.py --write` against the current `api_sentinel.py`.",
         "", "**Read this first.** The corpus is small, hand-built and adversarially chosen. These are counts of "
         "individual accesses (owner -> accessor, verb), not detection rates. A green test run means *the measured "
         "behaviour is what is pinned and the harness is sound*, not that the tool is correct.", "",
         f"Scenarios: **{tot['scenarios']}** | cases (fixtures): **{tot['cases']}** | oracle accesses: **{tot['accesses']}**",
         "", "## How outcomes are assigned", "",
         "| Oracle label (truth, verified by a direct probe) | Outcome when the tool ... | |",
         "|---|---|---|",
         "| VULNERABLE | confirms it -> TP; stays silent -> FN | |",
         "| SECURE | stays silent -> TN; confirms it -> FP | |",
         "| POLICY_DEPENDENT / INDETERMINATE | confirms -> UNDECIDABLE_FLAGGED; silent -> UNDECIDABLE_SILENT | the truth cannot be decided from the input |",
         "| any | returns an undetermined result -> UNDETERMINED | the tool declined to decide |",
         "| any | refused, setup failed, skipped or unreachable -> NEEDS_INPUT | the check did not run |",
         "| any | harness or tool crashed -> ERROR | never counted as TN |", "",
         "Verdict: PASS = TP or TN; FAIL = FP, FN or ERROR; NOT DECIDED = the rest.", "",
         "## Totals", "", "| Outcome | Count |", "|---|---|"]
    for k in OUTCOME_ORDER:
        L.append(f"| {k} | {c.get(k, 0)} |")
    L += ["", f"Verdicts: PASS {tot['pass']} | FAIL {tot['fail']} | NOT DECIDED {tot['not_decided']}",
          f"Requests sent to fixtures: {tot['requests_sent']} | residue left on targets: {tot['residue_left_on_target']}",
          f"Vulnerable accesses the tool declined to decide (recall lost to abstention): {tot['vulnerable_missed_only_by_abstention']}",
          "", "### By mode", "", "| Mode | " + " | ".join(OUTCOME_ORDER) + " |", "|---|" + "---|" * len(OUTCOME_ORDER)]
    for mode in ("matrix", "stateful", "cli"):
        mc = Counter(t.outcome for r in results if r.case.mode == mode for t in r.rows)
        L.append(f"| {mode} | " + " | ".join(str(mc.get(k, 0)) for k in OUTCOME_ORDER) + " |")
    L += ["", "## Vulnerable vs secure pairs: does the tool tell them apart?", "",
          "| Pair | Vulnerable flagged | Secure flagged | Verdict |", "|---|---|---|---|"]
    for name, _v, _s, vf, sf, verdict_text in harness.pair_table(results, scenarios.PAIRS):
        L.append(f"| {name} | {vf} | {sf} | {verdict_text} |")
    L += ["", "## Confidence calibration (every FINDING the tool emitted)", "",
          "| Confidence / severity | TP | FP | UNDECIDABLE_FLAGGED |", "|---|---|---|---|"]
    cal = defaultdict(Counter)
    for r in results:
        for t in r.rows:
            if t.state == "FINDING":
                cal[f"{t.confidence} / {t.severity}"][t.outcome] += 1
    for k in sorted(cal):
        L.append(f"| {k} | {cal[k]['TP']} | {cal[k]['FP']} | {cal[k]['UNDECIDABLE_FLAGGED']} |")
    L += ["", "## Gap register", ""]
    hit = defaultdict(list)
    for r in results:
        for t in r.rows:
            if t.outcome in DEVIATIONS:
                for g in filter(None, t.gap.split(",")):
                    hit[g].append(f"{t.case_id}:{t.owner}>{t.accessor}:{t.verb}={t.outcome}")
    for g, text in scenarios.GAPS.items():
        L.append(f"- **{g}** {text}")
        evidence = hit.get(g, [])
        L.append(f"  - evidence: {len(evidence)} access(es)" + (": " + "; ".join(evidence[:6])
                                                              + (" ..." if len(evidence) > 6 else "") if evidence else " (none observed)"))
    L += ["", "## Per-access results", ""]
    cur = None
    for r in results:
        if r.case.scenario != cur:
            cur = r.case.scenario
            L += ["", f"### {cur} - {r.case.title}", "",
                  "| Case | Mode | Owner > accessor | Verb | Oracle | Expected | Actual | Outcome | Conf / sev / score | Gap |",
                  "|---|---|---|---|---|---|---|---|---|---|"]
        for t in r.rows:
            cs = f"{t.confidence} / {t.severity} / {t.score:.0f}" if t.state == "FINDING" else ""
            L.append(f"| {t.case_id} | {t.mode} | {t.owner} > {t.accessor} | {t.verb} | {t.label} | {t.expected} | "
                     f"{t.state} | **{t.outcome}** | {cs} | {t.gap} |")
    L += ["", "## Why the truth is undecided (POLICY / INDETERMINATE accesses)", ""]
    seen = set()
    for r in results:
        for t in r.rows:
            if t.label in (harness.POLICY, harness.INDET) and (t.case_id, t.why) not in seen:
                seen.add((t.case_id, t.why))
                flagged = sum(1 for x in r.rows if x.label == t.label and x.state == "FINDING")
                tot_l = sum(1 for x in r.rows if x.label == t.label)
                L.append(f"- **{t.case_id}** ({t.label}; tool flagged {flagged}/{tot_l}): {t.why}")
    return "\n".join(L) + "\n"


def write_csv(results, path):
    cols = ["case_id", "scenario", "variant", "mode", "owner", "accessor", "verb", "label", "expected", "state",
            "outcome", "verdict", "confidence", "severity", "score", "gap", "oracle_verified", "why"]
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for r in results:
            for t in r.rows:
                w.writerow([t.case_id, t.scenario, t.variant, t.mode, t.owner, t.accessor, t.verb, t.label,
                            t.expected, t.state, t.outcome, t.verdict, t.confidence, t.severity, t.score, t.gap,
                            t.verified, t.why])


def main(argv):
    results = harness.run_all(scenarios.CASES)
    c = harness.counts(results)
    tot = harness.totals(results)
    print(f"scenarios={tot['scenarios']} cases={tot['cases']} accesses={tot['accesses']} "
          f"requests={tot['requests_sent']} residue={tot['residue_left_on_target']}")
    for k in OUTCOME_ORDER:
        print(f"  {k:22} {c.get(k, 0)}")
    print(f"  verdicts: PASS={tot['pass']} FAIL={tot['fail']} NOT_DECIDED={tot['not_decided']}")
    bad = [(r.case.id, "unlabeled findings", r.unlabeled) for r in results if r.unlabeled]
    bad += [(r.case.id, "fixture errors", r.fixture_errors) for r in results if r.fixture_errors]
    bad += [(r.case.id, "tool crash", r.tool_error) for r in results if r.tool_error]
    bad += [(t.case_id, "ORACLE NOT VERIFIED", f"{t.owner}>{t.accessor} {t.verb}: {t.verify_note}")
            for r in results for t in r.rows if not t.verified]
    for b in bad:
        print("HARNESS PROBLEM:", b)
    for t, msg in prediction_mismatches(results):
        print(f"PREDICTION MISMATCH {t.case_id} {t.owner}>{t.accessor} {t.verb} ({t.label}): {msg}")
    if "--update-baseline" in argv:
        BASELINE.write_text(json.dumps(harness.snapshot(results), indent=1) + "\n", encoding="utf-8")
        print("baseline written:", BASELINE)
    if "--write" in argv:
        write_csv(results, HERE / "results.csv")
        (ROOT / "docs").mkdir(exist_ok=True)
        (ROOT / "docs" / "TEST_MATRIX_RESULTS.md").write_text(render_md(results), encoding="utf-8")
        print("wrote results.csv and docs/TEST_MATRIX_RESULTS.md")
    harness_broken = bool(bad) or c.get("ERROR", 0) > 0
    return 1 if harness_broken else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
